### PR TITLE
Updated the UBFClient to help prevent concurrent DB UBFEvents. There exi...

### PR DESCRIPTION
**Pull request by jdye64**
...sted a small chance before that if the manual "postUBFCache" method was called by the application consuming the SDK that the list of unposted events could contain an event from the database query that was actually already making an attempt to be sent the Silverpop leading to multiple copies of the event being sent to Silverpop.

### CODE REVIEW

**Comment by iOSprototyping** [comment]
I've seen this behavior happen and other times not. We should think through hardening this so that it doesn't ever double post the same event twice in the same submission and never again after an accepted response. 

Thoughts? We just accepted your last pull into the main repo.

**Comment by bahzuercher** [comment]
version 1.1.0

**Review by ANNGOC1981 — COMMENTED** [review]
Analysis

**Comment by ANNGOC1981** [comment]
10

**Review by ANNGOC1981 — COMMENTED** [review]
10

**Pull request merged**
